// DO NOT INCLUDE IN PUBLIC SOURCE CONTROL (i.e. github)

// api keys
const FLICKR_API_KEY = "PUT_FLICKR_API_KEY_HERE";
const SHUTTER_CLIENT_ID = "PUT_SHUTTER_CLIENT_ID_HERE";
const SHUTTER_CLIENT_SECRET = "PUT_SHUTTER_CLIENT_SECRET_HERE";

module.exports = config;